apiVersion: batch/v1
kind: Job
metadata:
  generateName: job-calc-pi-
  labels:
    job/name: calc-pi
    job/all: "true"
    kueue.x-k8s.io/queue-name: user-queue
spec:
  parallelism: 1
  completions: 1
  template:
    spec:
      containers:
        - name: pi
          image: perl
          command:
            - "perl"
            - "-Mbignum=bpi"
            - "-wle"
            - "print bpi(2000)"
          resources:
            requests:
              cpu: 1
              memory: "200Mi"
      restartPolicy: Never
