---
apiVersion: v1
kind: Namespace
metadata:
  name: project-a
  labels:
    kueue.openshift.io/managed: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: project-b
  labels:
    kueue.openshift.io/managed: "true"
