apiVersion: batch/v1
kind: Job
metadata:
  generateName: low-priority-
  labels:
    job/name: sleep
    job/all: "true"
    kueue.x-k8s.io/queue-name: local-queue
    kueue.x-k8s.io/priority-class: dev-priority
spec:
  parallelism: 3
  completions: 3
  suspend: true
  template:
    spec:
      containers:
        - name: dummy-job
          image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
          args: ["1h"]
          resources:
            requests:
              cpu: 1
              memory: "200Mi"
      restartPolicy: Never
